---
- hosts: 172.31.27.82
  become: yes 
  tasks:
  - name: i want to execute linux command
    command: hostname
    register: myresult

  - name: i want display first task result
    debug: 
      msg: "{{myresult}}"

  - name: install git
    apt:
     name: git
     state: present
    when: myresult.stderr=="" 

  - name: install tree
    apt:
     name: tree
     state: present
    when: myresult.stderr!="" 
    