---
- hosts: 172.31.20.0
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
     name: apache2
     state: present
    notify: Restart apache2
    
  - name: copy index file into nodes
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: Restart apache2
  
  handlers:
  - name: Restart apache2
    service:
      name: apache2
      state: restart



