---
- hosts: 172.31.27.82
  become: yes 
  tasks:
  - name: install git
    apt:
     name: git
     state: present
    tags: mygit

  - name: install tree
    apt:
     name: tree
     sta: present
    tags: mytree

  - name: install wget
    apt:
     name: wget
     state: present
    tags: mywget