---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu nodes only
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"
  - name: i want to install webserver on RedHat nodes only
    yum:
     name: httpd
     state: present
    when: ansible_os_family=="RedHat"

  - name: i want to  start webserver on RedHat node only
    service:
     name: httpd
     state: started 
    when: ansible_os_family=="RedHat"